/** Demo catalog. Prices, ratings, and reviews are fictional. */
const rawProducts = [
  {
    id: "soundmini",
    name: "אוזניות אלחוטיות SoundMini",
    category: "אודיו",
    blurb: "אוזניות בלוטות׳ ליומיום, עם נרתיק טעינה.",
    pitch: "אלחוטיות, מתאימות לדרך ולבית הספר",
    uses: ["school"],
    size: "medium",
    tags: ["אוזניות", "בלוטות", "אלחוטיות", "headphones", "soundmini"],
    icon: "headphones",
    accent: "#0c6b58",
    similar: ["sportbuds", "wiredbuds"],
    offers: [
      { store: "מחסן החסכון", price: 149, shipping: 19, days: 6, condition: "refurbished", rating: 4.2, detail: "מחודש ונבדק, אחריות חצי שנה" },
      { store: "חנות הנקודה", price: 179, shipping: 15, days: 3, condition: "new", rating: 4.6, detail: "חדש, אחריות שנה" },
      { store: "מהיר עד הבית", price: 209, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "sportbuds",
    name: "אוזניות ספורט FitBeat",
    category: "אודיו",
    blurb: "אוזניות קטנות שעמידות לזיעה, בלי נרתיק גדול.",
    pitch: "זולות יותר, מיועדות לריצה ולספורט",
    uses: ["sport"],
    size: "small",
    tags: ["אוזניות", "ספורט", "אלחוטיות", "ריצה", "fitbeat"],
    icon: "headphones",
    accent: "#1d6a8a",
    similar: ["soundmini", "wiredbuds"],
    offers: [
      { store: "מחסן החסכון", price: 99, shipping: 15, days: 5, condition: "new", rating: 4.3, detail: "חדש, אחריות חצי שנה" },
      { store: "חנות הנקודה", price: 129, shipping: 10, days: 3, condition: "new", rating: 4.5, detail: "כולל שלושה זוגות אטמים" },
      { store: "מהיר עד הבית", price: 149, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "wiredbuds",
    name: "אוזניות חוטיות כיתתיות",
    category: "אודיו",
    blurb: "אוזניות עם חוט. אין מה לטעון, והמחיר נמוך.",
    pitch: "האפשרות הזולה: עם חוט, בלי טעינה",
    uses: ["school"],
    size: "small",
    tags: ["אוזניות", "חוטיות", "כיתתיות", "זולות"],
    icon: "headphones",
    accent: "#6d5a2b",
    similar: ["sportbuds", "soundmini"],
    offers: [
      { store: "מחסן החסכון", price: 45, shipping: 0, days: 7, condition: "new", rating: 4.1, detail: "משלוח חינם, מגיע לאט" },
      { store: "דיל ישיר", price: 39, shipping: 12, days: 5, condition: "new", rating: 4.4, detail: "חדש באריזה פשוטה" },
      { store: "חנות הנקודה", price: 59, shipping: 15, days: 2, condition: "new", rating: 4.6, detail: "אפשרות איסוף מהירה" },
    ],
  },
  {
    id: "bottle750",
    name: "בקבוק מים תרמי 750 מ״ל",
    category: "בית ספר",
    blurb: "שומר על שתייה קרה בערך 12 שעות.",
    pitch: "גדול יותר, נשאר קר לאורך יום לימודים",
    uses: ["school"],
    size: "large",
    tags: ["בקבוק", "מים", "תרמי", "750"],
    icon: "bottle",
    accent: "#0c6b58",
    similar: ["bottle500"],
    offers: [
      { store: "מחסן החסכון", price: 59, shipping: 18, days: 6, condition: "new", rating: 4.3, detail: "מכסה רגיל, אחריות חודשיים" },
      { store: "מהיר עד הבית", price: 89, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
      { store: "חנות הנקודה", price: 79, shipping: 15, days: 3, condition: "new", rating: 4.7, detail: "כולל מכסה קש" },
    ],
  },
  {
    id: "bottle500",
    name: "בקבוק מים קל 500 מ״ל",
    category: "בית ספר",
    blurb: "בקבוק קטן וקל שנכנס בקלות לתיק.",
    pitch: "קטן וזול יותר, פחות נפח",
    uses: ["school"],
    size: "small",
    tags: ["בקבוק", "מים", "500", "קל"],
    icon: "bottle",
    accent: "#1d6a8a",
    similar: ["bottle750"],
    offers: [
      { store: "מחסן החסכון", price: 42, shipping: 12, days: 6, condition: "new", rating: 4.2, detail: "פלסטיק קשיח" },
      { store: "דיל ישיר", price: 49, shipping: 10, days: 4, condition: "new", rating: 4.4, detail: "מכסה בורג פשוט" },
      { store: "מהיר עד הבית", price: 69, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "shoes",
    name: "נעלי ריצה קלות Sprint",
    category: "הנעלה",
    blurb: "נעל קלה לריצה ולשיעור ספורט.",
    pitch: "נעל ריצה, לא נעל ליום לימודים ארוך",
    uses: ["sport"],
    size: "medium",
    tags: ["נעליים", "נעלי", "ריצה", "ספורט", "sprint"],
    icon: "shoe",
    accent: "#8d3b2f",
    similar: ["schoolshoes"],
    offers: [
      { store: "מחסן החסכון", price: 199, shipping: 25, days: 7, condition: "new", rating: 4.2, detail: "מידות 35–40" },
      { store: "חנות הנקודה", price: 249, shipping: 0, days: 4, condition: "new", rating: 4.6, detail: "משלוח חינם, החלפה לפי מידה" },
      { store: "מהיר עד הבית", price: 279, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "מגיע מהר, בלי החלפת מידה" },
    ],
  },
  {
    id: "schoolshoes",
    name: "נעלי יומיום לבית הספר",
    category: "הנעלה",
    blurb: "נעל נוחה להליכה, לא מיועדת לריצה.",
    pitch: "נוחות ליום לימודים, זולות מנעלי הריצה",
    uses: ["school"],
    size: "medium",
    tags: ["נעליים", "נעלי", "בית ספר", "יומיום"],
    icon: "shoe",
    accent: "#6d5a2b",
    similar: ["shoes"],
    offers: [
      { store: "מחסן החסכון", price: 119, shipping: 20, days: 6, condition: "new", rating: 4.2, detail: "סוליה רכה" },
      { store: "דיל ישיר", price: 139, shipping: 15, days: 4, condition: "new", rating: 4.4, detail: "שרוכים חלופיים בקופסה" },
      { store: "מהיר עד הבית", price: 169, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "lego",
    name: "ערכת לגו תחנת חלל",
    category: "משחקים",
    blurb: "ערכה גדולה, בערך 840 חלקים.",
    pitch: "הערכה הגדולה, עם יותר חלקים",
    uses: ["play"],
    size: "large",
    tags: ["לגו", "חלל", "תחנת", "ערכה", "בנייה"],
    icon: "bricks",
    accent: "#0c6b58",
    similar: ["legocar"],
    offers: [
      { store: "מחסן החסכון", price: 249, shipping: 25, days: 8, condition: "new", rating: 4.3, detail: "קופסה עם פינה מעוכה, חלקים שלמים" },
      { store: "חנות הנקודה", price: 289, shipping: 0, days: 3, condition: "new", rating: 4.8, detail: "אריזה סגורה" },
      { store: "מהיר עד הבית", price: 319, shipping: 0, days: 1, condition: "new", rating: 4.9, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "legocar",
    name: "ערכת לגו מכונית מרוץ",
    category: "משחקים",
    blurb: "ערכה קטנה, בערך 180 חלקים.",
    pitch: "ערכה קטנה וזולה יותר",
    uses: ["play"],
    size: "small",
    tags: ["לגו", "מכונית", "מרוץ", "ערכה", "בנייה"],
    icon: "bricks",
    accent: "#8d3b2f",
    similar: ["lego"],
    offers: [
      { store: "מחסן החסכון", price: 89, shipping: 15, days: 6, condition: "new", rating: 4.3, detail: "מתאים לבנייה קצרה" },
      { store: "דיל ישיר", price: 99, shipping: 12, days: 4, condition: "new", rating: 4.5, detail: "הוראות בעברית" },
      { store: "מהיר עד הבית", price: 129, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "mouse",
    name: "עכבר גיימינג Swift",
    category: "מחשבים",
    blurb: "עכבר עם תאורה וכפתורים נוספים למשחקים.",
    pitch: "מיועד למשחקים, יקר יותר מעכבר רגיל",
    uses: ["gaming"],
    size: "medium",
    tags: ["עכבר", "גיימינג", "מחשב", "swift"],
    icon: "mouse",
    accent: "#1d6a8a",
    similar: ["mousebasic"],
    offers: [
      { store: "מחסן החסכון", price: 129, shipping: 19, days: 6, condition: "refurbished", rating: 4.1, detail: "מחודש, תאורה עובדת" },
      { store: "חנות הנקודה", price: 159, shipping: 15, days: 3, condition: "new", rating: 4.6, detail: "אחריות שנה" },
      { store: "מהיר עד הבית", price: 189, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "mousebasic",
    name: "עכבר רגיל לשיעורים",
    category: "מחשבים",
    blurb: "עכבר פשוט לעבודות ולשיעורים, בלי תאורה.",
    pitch: "פשוט וזול יותר, לא לגיימינג",
    uses: ["school"],
    size: "small",
    tags: ["עכבר", "שיעורים", "מחשב", "רגיל"],
    icon: "mouse",
    accent: "#6d5a2b",
    similar: ["mouse"],
    offers: [
      { store: "מחסן החסכון", price: 39, shipping: 15, days: 7, condition: "new", rating: 4.0, detail: "חוטי" },
      { store: "דיל ישיר", price: 49, shipping: 12, days: 4, condition: "new", rating: 4.3, detail: "שקט יחסית" },
      { store: "מהיר עד הבית", price: 79, shipping: 0, days: 1, condition: "new", rating: 4.6, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "power",
    name: "מטען נייד 10000",
    category: "מחשבים",
    blurb: "סוללה ניידת שמספיקה ליותר מטעינה אחת של טלפון.",
    pitch: "הקיבולת הגדולה יותר",
    uses: ["phone"],
    size: "large",
    tags: ["מטען", "נייד", "סוללה", "פאוור", "10000"],
    icon: "battery",
    accent: "#0c6b58",
    similar: ["powersmall"],
    offers: [
      { store: "מחסן החסכון", price: 89, shipping: 10, days: 9, condition: "new", rating: 4.2, detail: "10,000 מיליאמפר, מגיע לאט" },
      { store: "חנות הנקודה", price: 119, shipping: 0, days: 3, condition: "new", rating: 4.6, detail: "משלוח חינם תוך שלושה ימים" },
      { store: "מהיר עד הבית", price: 179, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "מגיע מהר, המחיר גבוה" },
    ],
  },
  {
    id: "powersmall",
    name: "מטען נייד קטן 5000",
    category: "מחשבים",
    blurb: "סוללה דקה לטעינה אחת בערך.",
    pitch: "קטן וזול יותר, מספיק לטעינה אחת",
    uses: ["phone"],
    size: "small",
    tags: ["מטען", "נייד", "סוללה", "5000", "קטן"],
    icon: "battery",
    accent: "#1d6a8a",
    similar: ["power"],
    offers: [
      { store: "מחסן החסכון", price: 45, shipping: 12, days: 6, condition: "new", rating: 4.1, detail: "5,000 מיליאמפר" },
      { store: "דיל ישיר", price: 49, shipping: 10, days: 4, condition: "new", rating: 4.4, detail: "כולל כבל קצר" },
      { store: "מהיר עד הבית", price: 69, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "ball",
    name: "כדור כדורגל מידה 5",
    category: "ספורט",
    blurb: "כדור רשמי למשחק, מידה 5.",
    pitch: "מתאים למשחק רשמי",
    uses: ["sport"],
    size: "large",
    tags: ["כדור", "כדורגל", "מידה 5", "ספורט"],
    icon: "ball",
    accent: "#8d3b2f",
    similar: ["balltrain"],
    offers: [
      { store: "מחסן החסכון", price: 69, shipping: 15, days: 5, condition: "new", rating: 4.4, detail: "תפור, למשחק בחצר" },
      { store: "חנות הנקודה", price: 79, shipping: 10, days: 3, condition: "new", rating: 4.6, detail: "כולל משאבה קטנה" },
      { store: "מהיר עד הבית", price: 99, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "balltrain",
    name: "כדור אימון לחצר",
    category: "ספורט",
    blurb: "כדור רך יותר לאימון, לא למשחק רשמי.",
    pitch: "זול יותר, פחות מתאים למשחק רשמי",
    uses: ["sport"],
    size: "medium",
    tags: ["כדור", "אימון", "חצר", "כדורגל"],
    icon: "ball",
    accent: "#6d5a2b",
    similar: ["ball"],
    offers: [
      { store: "מחסן החסכון", price: 35, shipping: 10, days: 6, condition: "new", rating: 4.0, detail: "רך יחסית" },
      { store: "דיל ישיר", price: 39, shipping: 12, days: 4, condition: "new", rating: 4.2, detail: "מתאים לחצר" },
      { store: "מהיר עד הבית", price: 59, shipping: 0, days: 1, condition: "new", rating: 4.5, detail: "משלוח חינם עד מחר" },
    ],
  },
];

const storeByName = {
  "חנות הנקודה": "nekuda",
  "מחסן החסכון": "machsan",
  "דיל ישיר": "deal",
  "מהיר עד הבית": "mahir",
};

const details = {
  soundmini: { brand: "SoundMini", colors: ["שחור", "לבן"], sizes: ["אחת"] },
  sportbuds: { brand: "FitBeat", colors: ["שחור", "כחול"], sizes: ["אחת"] },
  wiredbuds: { brand: "ClassBeat", colors: ["שחור", "לבן"], sizes: ["אחת"] },
  bottle750: { brand: "CoolSip", colors: ["כחול", "ירוק"], sizes: ["750 מ״ל"] },
  bottle500: { brand: "CoolSip", colors: ["כחול", "שקוף"], sizes: ["500 מ״ל"] },
  shoes: { brand: "Sprint", colors: ["שחור", "אפור"], sizes: ["37", "38", "39"] },
  schoolshoes: { brand: "Sprint", colors: ["שחור", "לבן"], sizes: ["36", "37", "38"] },
  lego: { brand: "Bricko", colors: ["צבעוני"], sizes: ["אחת"] },
  legocar: { brand: "Bricko", colors: ["אדום", "כחול"], sizes: ["אחת"] },
  mouse: { brand: "Swift", colors: ["שחור", "לבן"], sizes: ["אחת"] },
  mousebasic: { brand: "Swift", colors: ["שחור", "אפור"], sizes: ["אחת"] },
  power: { brand: "Volt", colors: ["שחור", "לבן"], sizes: ["10000"] },
  powersmall: { brand: "Volt", colors: ["לבן", "כחול"], sizes: ["5000"] },
  ball: { brand: "Kick", colors: ["לבן", "שחור"], sizes: ["5"] },
  balltrain: { brand: "Kick", colors: ["כתום", "צהוב"], sizes: ["4"] },
};

export const stores = [
  {
    id: "nekuda",
    name: "חנות הנקודה",
    channel: "store",
    place: "חנות ברחוב הרצל, תל אביב",
    rating: 4.6,
    reviewCount: 128,
    reviews: [
      { name: "נועה", stars: 5, text: "בדקו איתי את המידה בחנות ולא מיהרו." },
      { name: "אורי", stars: 4, text: "היה תור קצר, והמחיר על המדף היה ברור." },
    ],
  },
  {
    id: "machsan",
    name: "מחסן החסכון",
    channel: "store",
    place: "חנות במתחם העסקים, חולון",
    rating: 4.2,
    reviewCount: 86,
    reviews: [
      { name: "דניאל", stars: 4, text: "זול, אבל צריך לבדוק לבד שהקופסה שלמה." },
      { name: "מאיה", stars: 3, text: "מצאתי מחודש במחיר טוב. לקח כמה ימים עד שהגיע לסניף." },
    ],
  },
  {
    id: "deal",
    name: "דיל ישיר",
    channel: "online",
    place: "אתר מכירות",
    rating: 4.4,
    reviewCount: 240,
    reviews: [
      { name: "יובל", stars: 5, text: "ההזמנה באתר הייתה פשוטה והמעקב עבד." },
      { name: "תמר", stars: 4, text: "המשלוח הגיע יום אחרי מה שהבטיחו, אבל האריזה הייתה תקינה." },
    ],
  },
  {
    id: "mahir",
    name: "מהיר עד הבית",
    channel: "online",
    place: "אתר מכירות",
    rating: 4.8,
    reviewCount: 512,
    reviews: [
      { name: "ליאם", stars: 5, text: "הזמנתי בערב והחבילה הייתה בבית למחרת." },
      { name: "שירה", stars: 4, text: "יקר יותר מחנויות, ובתמורה המשלוח באמת מהיר." },
    ],
  },
  {
    id: "shuk",
    name: "אתר השוק",
    channel: "online",
    place: "אתר מכירות",
    rating: 4.1,
    reviewCount: 73,
    reviews: [
      { name: "עומר", stars: 4, text: "המוכר באתר ענה מהר על שאלה לגבי הצבע." },
      { name: "הילה", stars: 3, text: "המחיר היה טוב. החזרה למוכר לקחה יותר מדי זמן." },
    ],
  },
];

export const collectedFeed = [
  {
    productId: "soundmini",
    storeId: "shuk",
    price: 189,
    shipping: 0,
    days: 2,
    condition: "new",
    color: "לבן",
    sizeLabel: "אחת",
    detail: "דיווח שנאסף לקובץ הדוגמה, לא מאתר חי",
  },
];

export const products = rawProducts.map((product) => {
  const info = details[product.id];
  return {
    ...product,
    brand: info.brand,
    colors: info.colors,
    sizes: info.sizes,
    offers: product.offers.map((offer, index) => ({
      ...offer,
      storeId: storeByName[offer.store],
      condition: offer.condition === "refurbished" ? "used" : offer.condition,
      color: info.colors[index % info.colors.length],
      sizeLabel: info.sizes[index % info.sizes.length],
    })),
  };
});

export const examples = [
  "אוזניות עד 200 שקל, עדיף משלוח מהיר",
  "נעליים לשיעור ספורט, חדשות, ושלא ייקח שבוע",
  "לגו גדול עד 300",
  "בקבוק לתיק, לא ענק",
  "עכבר למשחקים, בלי מחודש, עד 160",
];
