/** Demo catalog. Prices are fictional and are not live store prices. */
export const products = [
  {
    id: "soundmini",
    name: "אוזניות אלחוטיות SoundMini",
    category: "אודיו",
    blurb: "אוזניות בלוטות׳ ליומיום, עם נרתיק טעינה.",
    pitch: "אלחוטיות, מתאימות לדרך ולבית הספר",
    uses: ["school"],
    size: "medium",
    tags: ["אוזניות", "בלוטות", "אלחוטיות", "headphones", "soundmini"],
    icon: "headphones",
    accent: "#0c6b58",
    similar: ["sportbuds", "wiredbuds"],
    offers: [
      { store: "מחסן החסכון", price: 149, shipping: 19, days: 6, condition: "refurbished", rating: 4.2, detail: "מחודש ונבדק, אחריות חצי שנה" },
      { store: "חנות הנקודה", price: 179, shipping: 15, days: 3, condition: "new", rating: 4.6, detail: "חדש, אחריות שנה" },
      { store: "מהיר עד הבית", price: 209, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "sportbuds",
    name: "אוזניות ספורט FitBeat",
    category: "אודיו",
    blurb: "אוזניות קטנות שעמידות לזיעה, בלי נרתיק גדול.",
    pitch: "זולות יותר, מיועדות לריצה ולספורט",
    uses: ["sport"],
    size: "small",
    tags: ["אוזניות", "ספורט", "אלחוטיות", "ריצה", "fitbeat"],
    icon: "headphones",
    accent: "#1d6a8a",
    similar: ["soundmini", "wiredbuds"],
    offers: [
      { store: "מחסן החסכון", price: 99, shipping: 15, days: 5, condition: "new", rating: 4.3, detail: "חדש, אחריות חצי שנה" },
      { store: "חנות הנקודה", price: 129, shipping: 10, days: 3, condition: "new", rating: 4.5, detail: "כולל שלושה זוגות אטמים" },
      { store: "מהיר עד הבית", price: 149, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "wiredbuds",
    name: "אוזניות חוטיות כיתתיות",
    category: "אודיו",
    blurb: "אוזניות עם חוט. אין מה לטעון, והמחיר נמוך.",
    pitch: "האפשרות הזולה: עם חוט, בלי טעינה",
    uses: ["school"],
    size: "small",
    tags: ["אוזניות", "חוטיות", "כיתתיות", "זולות"],
    icon: "headphones",
    accent: "#6d5a2b",
    similar: ["sportbuds", "soundmini"],
    offers: [
      { store: "מחסן החסכון", price: 45, shipping: 0, days: 7, condition: "new", rating: 4.1, detail: "משלוח חינם, מגיע לאט" },
      { store: "דיל ישיר", price: 39, shipping: 12, days: 5, condition: "new", rating: 4.4, detail: "חדש באריזה פשוטה" },
      { store: "חנות הנקודה", price: 59, shipping: 15, days: 2, condition: "new", rating: 4.6, detail: "אפשרות איסוף מהירה" },
    ],
  },
  {
    id: "bottle750",
    name: "בקבוק מים תרמי 750 מ״ל",
    category: "בית ספר",
    blurb: "שומר על שתייה קרה בערך 12 שעות.",
    pitch: "גדול יותר, נשאר קר לאורך יום לימודים",
    uses: ["school"],
    size: "large",
    tags: ["בקבוק", "מים", "תרמי", "750"],
    icon: "bottle",
    accent: "#0c6b58",
    similar: ["bottle500"],
    offers: [
      { store: "מחסן החסכון", price: 59, shipping: 18, days: 6, condition: "new", rating: 4.3, detail: "מכסה רגיל, אחריות חודשיים" },
      { store: "מהיר עד הבית", price: 89, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
      { store: "חנות הנקודה", price: 79, shipping: 15, days: 3, condition: "new", rating: 4.7, detail: "כולל מכסה קש" },
    ],
  },
  {
    id: "bottle500",
    name: "בקבוק מים קל 500 מ״ל",
    category: "בית ספר",
    blurb: "בקבוק קטן וקל שנכנס בקלות לתיק.",
    pitch: "קטן וזול יותר, פחות נפח",
    uses: ["school"],
    size: "small",
    tags: ["בקבוק", "מים", "500", "קל"],
    icon: "bottle",
    accent: "#1d6a8a",
    similar: ["bottle750"],
    offers: [
      { store: "מחסן החסכון", price: 42, shipping: 12, days: 6, condition: "new", rating: 4.2, detail: "פלסטיק קשיח" },
      { store: "דיל ישיר", price: 49, shipping: 10, days: 4, condition: "new", rating: 4.4, detail: "מכסה בורג פשוט" },
      { store: "מהיר עד הבית", price: 69, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "shoes",
    name: "נעלי ריצה קלות Sprint",
    category: "הנעלה",
    blurb: "נעל קלה לריצה ולשיעור ספורט.",
    pitch: "נעל ריצה, לא נעל ליום לימודים ארוך",
    uses: ["sport"],
    size: "medium",
    tags: ["נעליים", "נעלי", "ריצה", "ספורט", "sprint"],
    icon: "shoe",
    accent: "#8d3b2f",
    similar: ["schoolshoes"],
    offers: [
      { store: "מחסן החסכון", price: 199, shipping: 25, days: 7, condition: "new", rating: 4.2, detail: "מידות 35–40" },
      { store: "חנות הנקודה", price: 249, shipping: 0, days: 4, condition: "new", rating: 4.6, detail: "משלוח חינם, החלפה לפי מידה" },
      { store: "מהיר עד הבית", price: 279, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "מגיע מהר, בלי החלפת מידה" },
    ],
  },
  {
    id: "schoolshoes",
    name: "נעלי יומיום לבית הספר",
    category: "הנעלה",
    blurb: "נעל נוחה להליכה, לא מיועדת לריצה.",
    pitch: "נוחות ליום לימודים, זולות מנעלי הריצה",
    uses: ["school"],
    size: "medium",
    tags: ["נעליים", "נעלי", "בית ספר", "יומיום"],
    icon: "shoe",
    accent: "#6d5a2b",
    similar: ["shoes"],
    offers: [
      { store: "מחסן החסכון", price: 119, shipping: 20, days: 6, condition: "new", rating: 4.2, detail: "סוליה רכה" },
      { store: "דיל ישיר", price: 139, shipping: 15, days: 4, condition: "new", rating: 4.4, detail: "שרוכים חלופיים בקופסה" },
      { store: "מהיר עד הבית", price: 169, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "lego",
    name: "ערכת לגו תחנת חלל",
    category: "משחקים",
    blurb: "ערכה גדולה, בערך 840 חלקים.",
    pitch: "הערכה הגדולה, עם יותר חלקים",
    uses: ["play"],
    size: "large",
    tags: ["לגו", "חלל", "תחנת", "ערכה", "בנייה"],
    icon: "bricks",
    accent: "#0c6b58",
    similar: ["legocar"],
    offers: [
      { store: "מחסן החסכון", price: 249, shipping: 25, days: 8, condition: "new", rating: 4.3, detail: "קופסה עם פינה מעוכה, חלקים שלמים" },
      { store: "חנות הנקודה", price: 289, shipping: 0, days: 3, condition: "new", rating: 4.8, detail: "אריזה סגורה" },
      { store: "מהיר עד הבית", price: 319, shipping: 0, days: 1, condition: "new", rating: 4.9, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "legocar",
    name: "ערכת לגו מכונית מרוץ",
    category: "משחקים",
    blurb: "ערכה קטנה, בערך 180 חלקים.",
    pitch: "ערכה קטנה וזולה יותר",
    uses: ["play"],
    size: "small",
    tags: ["לגו", "מכונית", "מרוץ", "ערכה", "בנייה"],
    icon: "bricks",
    accent: "#8d3b2f",
    similar: ["lego"],
    offers: [
      { store: "מחסן החסכון", price: 89, shipping: 15, days: 6, condition: "new", rating: 4.3, detail: "מתאים לבנייה קצרה" },
      { store: "דיל ישיר", price: 99, shipping: 12, days: 4, condition: "new", rating: 4.5, detail: "הוראות בעברית" },
      { store: "מהיר עד הבית", price: 129, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "mouse",
    name: "עכבר גיימינג Swift",
    category: "מחשבים",
    blurb: "עכבר עם תאורה וכפתורים נוספים למשחקים.",
    pitch: "מיועד למשחקים, יקר יותר מעכבר רגיל",
    uses: ["gaming"],
    size: "medium",
    tags: ["עכבר", "גיימינג", "מחשב", "swift"],
    icon: "mouse",
    accent: "#1d6a8a",
    similar: ["mousebasic"],
    offers: [
      { store: "מחסן החסכון", price: 129, shipping: 19, days: 6, condition: "refurbished", rating: 4.1, detail: "מחודש, תאורה עובדת" },
      { store: "חנות הנקודה", price: 159, shipping: 15, days: 3, condition: "new", rating: 4.6, detail: "אחריות שנה" },
      { store: "מהיר עד הבית", price: 189, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "משלוח חינם שמגיע מהר" },
    ],
  },
  {
    id: "mousebasic",
    name: "עכבר רגיל לשיעורים",
    category: "מחשבים",
    blurb: "עכבר פשוט לעבודות ולשיעורים, בלי תאורה.",
    pitch: "פשוט וזול יותר, לא לגיימינג",
    uses: ["school"],
    size: "small",
    tags: ["עכבר", "שיעורים", "מחשב", "רגיל"],
    icon: "mouse",
    accent: "#6d5a2b",
    similar: ["mouse"],
    offers: [
      { store: "מחסן החסכון", price: 39, shipping: 15, days: 7, condition: "new", rating: 4.0, detail: "חוטי" },
      { store: "דיל ישיר", price: 49, shipping: 12, days: 4, condition: "new", rating: 4.3, detail: "שקט יחסית" },
      { store: "מהיר עד הבית", price: 79, shipping: 0, days: 1, condition: "new", rating: 4.6, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "power",
    name: "מטען נייד 10000",
    category: "מחשבים",
    blurb: "סוללה ניידת שמספיקה ליותר מטעינה אחת של טלפון.",
    pitch: "הקיבולת הגדולה יותר",
    uses: ["phone"],
    size: "large",
    tags: ["מטען", "נייד", "סוללה", "פאוור", "10000"],
    icon: "battery",
    accent: "#0c6b58",
    similar: ["powersmall"],
    offers: [
      { store: "מחסן החסכון", price: 89, shipping: 10, days: 9, condition: "new", rating: 4.2, detail: "10,000 מיליאמפר, מגיע לאט" },
      { store: "חנות הנקודה", price: 119, shipping: 0, days: 3, condition: "new", rating: 4.6, detail: "משלוח חינם תוך שלושה ימים" },
      { store: "מהיר עד הבית", price: 179, shipping: 0, days: 1, condition: "new", rating: 4.8, detail: "מגיע מהר, המחיר גבוה" },
    ],
  },
  {
    id: "powersmall",
    name: "מטען נייד קטן 5000",
    category: "מחשבים",
    blurb: "סוללה דקה לטעינה אחת בערך.",
    pitch: "קטן וזול יותר, מספיק לטעינה אחת",
    uses: ["phone"],
    size: "small",
    tags: ["מטען", "נייד", "סוללה", "5000", "קטן"],
    icon: "battery",
    accent: "#1d6a8a",
    similar: ["power"],
    offers: [
      { store: "מחסן החסכון", price: 45, shipping: 12, days: 6, condition: "new", rating: 4.1, detail: "5,000 מיליאמפר" },
      { store: "דיל ישיר", price: 49, shipping: 10, days: 4, condition: "new", rating: 4.4, detail: "כולל כבל קצר" },
      { store: "מהיר עד הבית", price: 69, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "ball",
    name: "כדור כדורגל מידה 5",
    category: "ספורט",
    blurb: "כדור רשמי למשחק, מידה 5.",
    pitch: "מתאים למשחק רשמי",
    uses: ["sport"],
    size: "large",
    tags: ["כדור", "כדורגל", "מידה 5", "ספורט"],
    icon: "ball",
    accent: "#8d3b2f",
    similar: ["balltrain"],
    offers: [
      { store: "מחסן החסכון", price: 69, shipping: 15, days: 5, condition: "new", rating: 4.4, detail: "תפור, למשחק בחצר" },
      { store: "חנות הנקודה", price: 79, shipping: 10, days: 3, condition: "new", rating: 4.6, detail: "כולל משאבה קטנה" },
      { store: "מהיר עד הבית", price: 99, shipping: 0, days: 1, condition: "new", rating: 4.7, detail: "משלוח חינם עד מחר" },
    ],
  },
  {
    id: "balltrain",
    name: "כדור אימון לחצר",
    category: "ספורט",
    blurb: "כדור רך יותר לאימון, לא למשחק רשמי.",
    pitch: "זול יותר, פחות מתאים למשחק רשמי",
    uses: ["sport"],
    size: "medium",
    tags: ["כדור", "אימון", "חצר", "כדורגל"],
    icon: "ball",
    accent: "#6d5a2b",
    similar: ["ball"],
    offers: [
      { store: "מחסן החסכון", price: 35, shipping: 10, days: 6, condition: "new", rating: 4.0, detail: "רך יחסית" },
      { store: "דיל ישיר", price: 39, shipping: 12, days: 4, condition: "new", rating: 4.2, detail: "מתאים לחצר" },
      { store: "מהיר עד הבית", price: 59, shipping: 0, days: 1, condition: "new", rating: 4.5, detail: "משלוח חינם עד מחר" },
    ],
  },
];

export const examples = [
  "אוזניות עד 200 שקל, עדיף משלוח מהיר",
  "נעליים לשיעור ספורט, חדשות, ושלא ייקח שבוע",
  "לגו גדול עד 300",
  "בקבוק לתיק, לא ענק",
  "עכבר למשחקים, בלי מחודש, עד 160",
];
